# Generated by Django 5.1.4 on 2025-01-06 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtchat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgroup",
            name="users_online",
            field=models.ManyToManyField(
                blank=True, related_name="online_in_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
