# Generated by Django 5.1.4 on 2025-01-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_freelancer_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="displayname",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
